services:
  - type: web
    name: password-generator-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production



